sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

env:
- DOCKER_IMAGE=gsas/rso-buyers

script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push "$DOCKER_IMAGE"
