version: "2"
services:
  rso-customers:
    image: gsas/rso-buyers

    ports:
      - 8081:8081
      - 8000:8081

    depends_on:
      - etcd

    volumes:
      #- ./api/target/api-1.0-SNAPSHOT.jar:/app.jar
      - ./api/target/api-1.0-SNAPSHOT.jar:/api/target/api-1.0-SNAPSHOT.jar

    command:
      java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -jar buyers-api-1.0-SNAPSHOT.jar
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
    - "2379:2379"
    command: >-
      /usr/local/bin/etcd
      -name node1
      -advertise-client-urls http://0.0.0.0:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster node1=http://etcd:2380
      -cors="*"

