kumuluzee:
  name: rso-buyer
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    etcd:
      hosts: http://etcd:2379
  discovery:
    etcd:
      hosts: http://etcd:2379
    ttl: 60
    ping-interval: 60

rest-properties:
  faultTolerance: false

info-properties:
  member1: as4813
  member2: gs8150
  description: Nas projekt implementira platformo za narocanje hrane
  service-buyer: "http://137.117.255.32:8081/v1/buyers"
  service-order: "http://40.115.23.25:8082/v1/orders"
  github-buyer: "https://github.com/FRIRSO/rso-buyer"
  github-order: "https://github.com/FRIRSO/rso-order"
  travis-buyer: "https://travis-ci.org/FRIRSO/rso-buyer"
  travis-order: "https://travis-ci.org/FRIRSO/rso-order"
  docker-buyer: "https://hub.docker.com/r/gsas/rso-buyers/"
  docker-order: "https://hub.docker.com/r/gsas/rso-orders/"

db-properties:
  db-user: root
  db-pass: 13tpxnxJTwUScc3V
  db-name: rso-projekt