kumuluzee:
  name: rso-buyer
  env:
    name: dev
  version: 1.0.
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    etcd:
      hosts: http://192.168.1.135:2379
  discovery:
    etcd:
      hosts: http://192.168.1.135:2379
    ttl: 60
    ping-interval: 60
app-properties:
  external-services:
    enabled: false
  healthy: true
  member1: true

info-properties:
  member1: as4813
  member2: gx0000
  description: "Nas projekt implementira platformo za narocanje hrane."
  serviceBuyer: address1
  serviceOrder: address2
  githubBuyer: https://github.com/FRIRSO/rso-buyer
  githubOrder: https://github.com/FRIRSO/rso-order
  travisBuyer: https://travis-ci.org/FRIRSO/rso-buyer
  travisOrder: https://travis-ci.org/FRIRSO/rso-order
  dockerBuyer: https://hub.docker.com/r/gsas/rso-buyers/
  dockerOrder: https://hub.docker.com/r/gsas/rso-orders/
